### ISSUE TITLE
[Other issue]: move crate dependencies to workspace dependencies.

### ISSUE THREAD

**Issue by rydb** [open-rmf/rmf_sandbox#288]
### Before proceeding, is there an existing issue or discussion for this?

- [x] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### Description

For the sake of streamlining updating dependencies across crates, and to reduce the risk of duplicate dependencies, crate dependencies should be confederated under workspace dependencies, so imports can just be reduced to just: 

```toml
# dependent Cargo.toml
[dependencies]
bevy = {workspace = true}
dependency2 = {workspace = true, features = ["feature1", "feature2"]}
# etc etc


# root Cargo.toml
[workspace.dependencies]
bevy = {version = "0.16"}
dependency2 = {version = "???"}
```
